version: '3.9'

services:
  web:
    build:
      context: ../odoo
      dockerfile: ../.devcontainer/Dockerfile
    container_name: odoo_dev_web
    user: "root"
    environment:
      # Updated HOST to point to the external PostgreSQL container's name
      - HOST=postgres-dev
      - USER=odoo_user
      - PASSWORD=jajnav5@
      - DATABASE=odoo
      - PGUSER=odoo_user
      - PGPASSWORD=jajnav5@
      - PGHOST=postgres-dev
      - PGDATABASE=odoo
      - PGPORT=5432
      - PGSSLMODE=disable
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - keycloak-dbs-brokers_backend_network
    ports:
      - "8069:8069"
      - "8071:8071" # Odoo's live chat
    volumes:
      - ../odoo:/usr/lib/python3/dist-packages/odoo # Mount Odoo source code
      - ../addons:/mnt/extra-addons # Custom addons
      - ../..:/workspaces:cached
    working_dir: /workspaces
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    restart: always

networks:
  keycloak-dbs-brokers_backend_network:
    external: true
    name: keycloak-dbs-brokers_backend_network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: keycloak-dbs-brokers_backend_network
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 237.84.2.178/16
          gateway: 237.84.2.178